title: Jayden's Website
email: Jaydensnarr@mail.weber.edu
description: >- # this means to ignore newlines until "baseurl:"
  SnowBidPro is my first websit SAAS that helps snow contractors collect customers, automates communication based on snow forecasts, and automates customer onboarding. 
logo: "/assets/images/logo.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# Build settings
theme: "jekyll-theme-minimal"
